[versions]
minecraft     = "1.21.5"
fabric-loader = "0.16.13"
parchment     = "1.21.5:2025.04.19"
fabric-api    = "0.120.0+1.21.5"
fabric-kotlin = "1.13.2+kotlin.2.1.20"
permissions   = "0.3.3"
inject        = "3.1.3"

# Compatability depdendencies
carpet        = "1.4.169"
voicechat     = "fabric-1.21.5-2.5.30"
voicechat-api = "2.5.27"
vmp           = "0.2.0+beta.7.198+1.21.5"
c2me          = "0.3.2+rc.1.0+1.21.5"
polymer       = "0.12.3+1.21.5"
replay-studio = "aa5ab3a302"

# Plugins
fabric-loom   = "1.10-SNAPSHOT"
mod-publish   = "0.8.1"
shadow        = "8.3.5"
explosion     = "0.3.1"

[libraries]
minecraft     = { module = "com.mojang:minecraft"               , version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader"         , version.ref = "fabric-loader" }
fabric-api    = { module = "net.fabricmc.fabric-api:fabric-api" , version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
permissions   = { module = "me.lucko:fabric-permissions-api"    , version.ref = "permissions" }
replay-studio = { module = "com.github.ReplayMod:ReplayStudio"  , version.ref = "replay-studio" }
inject-api    = { module = "net.mcbrawls.inject:api"            , version.ref = "inject" }
inject-http   = { module = "net.mcbrawls.inject:http"           , version.ref = "inject" }
inject-fabric = { module = "net.mcbrawls.inject:fabric"         , version.ref = "inject" }

# Compatability depdendencies
carpet        = { module = "com.github.gnembon:fabric-carpet"    , version.ref = "carpet" }
voicechat     = { module = "maven.modrinth:simple-voice-chat"    , version.ref = "voicechat" }
voicechat-api = { module = "de.maxhenkel.voicechat:voicechat-api", version.ref = "voicechat-api" }
vmp           = { module = "maven.modrinth:vmp-fabric"           , version.ref = "vmp" }
c2me          = { module = "maven.modrinth:c2me-fabric"          , version.ref = "c2me" }
polymer-core  = { module = "eu.pb4:polymer-core"                 , version.ref = "polymer" }

[plugins]
fabric-loom = { id = "fabric-loom"                    , version.ref = "fabric-loom" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
shadow      = { id = "com.gradleup.shadow"            , version.ref = "shadow" }
explosion   = { id = "lol.bai.explosion"              , version.ref = "explosion"}